profile: cover.out
local-prefix: "go_clean_architecture"
threshold:
  file: 60
  package: 80
  total: 80
exclude:
  paths:
    - \.pb\.go$    # excludes all protobuf generated files
    - \mocks?\.go$ # excludes all mock files