profile: cover.out
local-prefix: "go_clean_architecture"
threshold:
  file: 60
  package: 80
  total: 80
exclude:
  paths:
    - \.pb\.go$    # excludes all protobuf generated files
    - \mocks?\.go$ # excludes all mock files
    - \docs/.*\.go$ # excludes all docs files
    - \internal/docs/.*\.go$ # excludes all internal/docs files
    - \internal/infrastucture/.*\.go$ # excludes all internal/infrastucture files