profile: cover.out
local-prefix: "github.com/intama-oss/go-clean-architecture"
threshold:
  file: 60
  package: 80
  total: 80
exclude:
  paths:
    - \.pb\.go$ # excludes all protobuf generated files
    - mocks/ # excludes all mocks
    - docs/ # excludes all documentation
    - cmd/ # excludes all command line interfaces
    - internal/infrastructure/ # excludes all infrastructure