name: Tes Cakupan Kode
run-name: Tes Cakupan Kode

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Generate Test Coverage
        run: go test ./... -coverprofile=./cover.out

      - name: Check Test Coverage
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml